on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Contiki-NG repo
        uses: actions/checkout@v3
        with:
          repository: contiki-ng/contiki-ng
          path: contiki-ng
      - uses: actions/checkout@v3
        with:
          repository: contiki-ng/cooja
          path: contiki-ng/tools/cooja
      - name: Setup Java 20
        uses: actions/setup-java@v3
        with:
          java-version: 20
          distribution: 'zulu'
      - name: Verify gradle-wrapper checksum
        uses: gradle/wrapper-validation-action@v1
      - name: Build Cooja and Documentation
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.3
          cache-read-only: false
          arguments: jar
          build-root-directory: contiki-ng/tools/cooja
      - name: Test MSPSim
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.3
          arguments: test
          build-root-directory: contiki-ng/tools/cooja

      - name: Run Contiki-NG simulation tests
        run: |
          cd contiki-ng/tests/07-simulation-base
          # Skip MSP430 tests, no compiler installed.
          rm ??-*sky*.csc ??-*z1*.csc
          source ../../tools/docker/files/bash_aliases
          cimake
