on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'
      - name: Verify gradle-wrapper checksum
        uses: gradle/wrapper-validation-action@v1
      - name: Build Cooja and Documentation
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.2
          cache-read-only: false
          arguments: jar
      - name: Test MSPSim
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.2
          arguments: test
